import datetime
# Import UserMixin and RoleMixin from Flask-Security
from flask_security import UserMixin, RoleMixin
# Import db instance from your database setup file
from applications.database import db

# Association Table for User-Role Many-to-Many relationship (Required by Flask-Security)
user_roles = db.Table('user_roles',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)

class Role(db.Model, RoleMixin):
    """
    Represents a user role (e.g., 'admin', 'user').
    Inherits RoleMixin for Flask-Security compatibility.
    """
    __tablename__ = 'role'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False) # Role name (e.g., 'admin')
    description = db.Column(db.String(255)) # Optional description

    def __repr__(self):
        return f'<Role {self.name}>'

class User(db.Model, UserMixin):
    """
    Represents a user account.
    Inherits UserMixin for Flask-Security compatibility.
    """
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    # Use 'email' for login if preferred by Flask-Security config, otherwise 'username'
    # Check your user_datastore setup if using email vs username. Assuming username for now.
    username = db.Column(db.String(80), unique=True, nullable=False)
    # IMPORTANT: Field must be named 'password' for Flask-Security's default hashing/verification
    password = db.Column(db.String(255), nullable=False) # Stores the hash generated by Flask-Security
    email = db.Column(db.String(120), unique=True, nullable=True) # Unique email is good practice
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow) # Track creation time
    # Required fields for Flask-Security:
    active = db.Column(db.Boolean()) # Is the user account active?
    fs_uniquifier = db.Column(db.String(64), unique=True, nullable=False) # Security stamp

    # Relationship to Role model via the user_roles association table
    roles = db.relationship('Role', secondary=user_roles,
                            backref=db.backref('users', lazy='dynamic'))

    # Relationship to Watchlist items (One-to-Many)
    watchlist_items = db.relationship('Watchlist', backref='owner', lazy=True, cascade='all, delete-orphan')

    # REMOVED custom set_password and check_password methods.
    # Flask-Security (via user_datastore.create_user and utils.verify_password) handles hashing.

    def __repr__(self):
        return f'<User {self.username}>'

class Watchlist(db.Model):
    """
    Represents a stock ticker saved by a user.
    """
    __tablename__ = 'watchlist'

    id = db.Column(db.Integer, primary_key=True)
    # Foreign Key linking back to the User who owns this item
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    ticker = db.Column(db.String(10), nullable=False) # Stock symbol
    notes = db.Column(db.String(200), nullable=True) # Optional user notes
    added_at = db.Column(db.DateTime, default=datetime.datetime.utcnow) # Track when added

    # Ensure a specific user cannot add the same ticker multiple times
    __table_args__ = (db.UniqueConstraint('user_id', 'ticker', name='_user_ticker_uc'),)

    def to_dict(self):
        """Helper method to convert object to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "ticker": self.ticker,
            "notes": self.notes if self.notes else "",
            "user_id": self.user_id,
            "added_at": self.added_at.isoformat() if self.added_at else None
        }

    def __repr__(self):
        return f'<Watchlist Ticker:{self.ticker} UserID:{self.user_id}>'

class PortfolioHolding(db.Model):
    """
    Represents a stock holding in a user's portfolio.
    Tracks quantity, purchase price, purchase date, and calculates current value.
    """
    __tablename__ = 'portfolio_holding'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    symbol = db.Column(db.String(20), nullable=False)  # Stock ticker (e.g., 'TCS.NS')
    quantity = db.Column(db.Float, nullable=False)  # Number of shares owned
    purchase_price = db.Column(db.Float, nullable=False)  # Purchase price per share
    purchase_date = db.Column(db.DateTime, nullable=False)  # When the stock was purchased
    notes = db.Column(db.Text, nullable=True)  # Optional user notes
    added_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Allow multiple purchases of same stock (no unique constraint on symbol)
    # Each transaction is a separate record

    def to_dict(self, current_price=None):
        """
        Convert to dictionary with calculated values.
        current_price: Current market price per share (fetched from yfinance)
        """
        total_invested = round(self.quantity * self.purchase_price, 2)
        current_value = round(self.quantity * current_price, 2) if current_price else total_invested
        gain_loss = round(current_value - total_invested, 2)
        gain_loss_percent = round((gain_loss / total_invested * 100), 2) if total_invested != 0 else 0

        return {
            'id': self.id,
            'symbol': self.symbol,
            'quantity': self.quantity,
            'purchase_price': self.purchase_price,
            'purchase_date': self.purchase_date.isoformat() if self.purchase_date else None,
            'notes': self.notes,
            'current_price': current_price,
            'total_invested': total_invested,
            'current_value': current_value,
            'gain_loss': gain_loss,
            'gain_loss_percent': gain_loss_percent,
            'added_at': self.added_at.isoformat() if self.added_at else None,
        }

    def __repr__(self):
        return f'<PortfolioHolding {self.symbol} Qty:{self.quantity} UserID:{self.user_id}>'


class PortfolioSnapshot(db.Model):
    """
    Historical snapshot of portfolio value for performance tracking.
    Stores total portfolio value at a specific point in time.
    """
    __tablename__ = 'portfolio_snapshot'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    total_value = db.Column(db.Float, nullable=False)  # Total portfolio value at this snapshot
    snapshot_date = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    
    # Ensure one snapshot per user per day (approximately)
    __table_args__ = (db.Index('_user_date_idx', 'user_id', 'snapshot_date'),)

    def to_dict(self):
        return {
            'id': self.id,
            'total_value': self.total_value,
            'snapshot_date': self.snapshot_date.isoformat() if self.snapshot_date else None,
        }

    def __repr__(self):
        return f'<PortfolioSnapshot UserID:{self.user_id} Value:{self.total_value} Date:{self.snapshot_date}>'


class InvestmentGoal(db.Model):
    """
    Represents a financial goal for the user.
    Tracks target amount, target date, and investment contribution requirements.
    """
    __tablename__ = 'investment_goal'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    goal_name = db.Column(db.String(100), nullable=False)  # e.g., "House", "Retirement", "Car"
    description = db.Column(db.String(500), nullable=True)
    target_amount = db.Column(db.Float, nullable=False)  # Amount needed (in ₹)
    current_amount = db.Column(db.Float, default=0)  # Amount saved so far
    target_date = db.Column(db.DateTime, nullable=False)  # Target completion date
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def to_dict(self):
        import datetime as dt
        now = datetime.datetime.utcnow()
        time_remaining = (self.target_date - now).days
        progress_percent = round((self.current_amount / self.target_amount * 100), 2) if self.target_amount != 0 else 0
        months_remaining = max(1, time_remaining // 30)
        monthly_needed = round((self.target_amount - self.current_amount) / months_remaining, 2) if months_remaining > 0 else 0

        return {
            'id': self.id,
            'goal_name': self.goal_name,
            'description': self.description,
            'target_amount': self.target_amount,
            'current_amount': self.current_amount,
            'target_date': self.target_date.isoformat() if self.target_date else None,
            'progress_percent': progress_percent,
            'amount_remaining': round(self.target_amount - self.current_amount, 2),
            'days_remaining': time_remaining,
            'months_remaining': months_remaining,
            'monthly_contribution_needed': monthly_needed,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f'<InvestmentGoal {self.goal_name} UserID:{self.user_id} Target:₹{self.target_amount}>'


class InvestmentClub(db.Model):
    """
    Represents an investment club where users can share insights and track collective investments.
    """
    __tablename__ = 'investment_club'

    id = db.Column(db.Integer, primary_key=True)
    club_name = db.Column(db.String(100), nullable=False)
    join_code = db.Column(db.String(20), unique=True, nullable=False)  # e.g., "CLUB-ABC123"
    created_by = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    
    # Relationships
    members = db.relationship('ClubMember', backref='club', lazy=True, cascade='all, delete-orphan')
    sharing_settings = db.relationship('ClubSharing', backref='club', lazy=True, cascade='all, delete-orphan')

    def to_dict(self):
        return {
            'id': self.id,
            'club_name': self.club_name,
            'join_code': self.join_code,
            'created_by': self.created_by,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'total_members': len(self.members)
        }

    def __repr__(self):
        return f'<InvestmentClub {self.club_name} ID:{self.id}>'


class ClubMember(db.Model):
    """
    Represents a member of an investment club.
    Tracks membership role and join date.
    """
    __tablename__ = 'club_member'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    club_id = db.Column(db.Integer, db.ForeignKey('investment_club.id'), nullable=False)
    role = db.Column(db.String(20), default='member', nullable=False)  # 'admin' or 'member'
    joined_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    
    # Ensure unique membership
    __table_args__ = (db.UniqueConstraint('user_id', 'club_id', name='_user_club_uc'),)

    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'club_id': self.club_id,
            'role': self.role,
            'joined_at': self.joined_at.isoformat() if self.joined_at else None
        }

    def __repr__(self):
        return f'<ClubMember UserID:{self.user_id} ClubID:{self.club_id} Role:{self.role}>'


class ClubSharing(db.Model):
    """
    Represents sharing preferences for a club member.
    Controls what portfolio data is visible to other club members.
    """
    __tablename__ = 'club_sharing'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    club_id = db.Column(db.Integer, db.ForeignKey('investment_club.id'), nullable=False)
    
    # Sharing preferences
    share_portfolio_value = db.Column(db.Boolean, default=False)
    share_holdings_list = db.Column(db.Boolean, default=False)
    share_performance = db.Column(db.Boolean, default=False)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
    
    # Ensure unique sharing setting per user per club
    __table_args__ = (db.UniqueConstraint('user_id', 'club_id', name='_user_club_sharing_uc'),)

    def to_dict(self):
        return {
            'id': self.id,
            'user_id': self.user_id,
            'club_id': self.club_id,
            'share_portfolio_value': self.share_portfolio_value,
            'share_holdings_list': self.share_holdings_list,
            'share_performance': self.share_performance,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

    def __repr__(self):
        return f'<ClubSharing UserID:{self.user_id} ClubID:{self.club_id}>'

